#!/bin/sh

make -C kernel bos.kernel

mkdir -p iso
mkdir -p iso/boot
mkdir -p iso/boot/grub

cp kernel/bos.kernel iso/boot/bos.kernel
cat > iso/boot/grub/grub.cfg << EOF
menuentry "BOS" {
	multiboot /boot/bos.kernel
}
EOF
grub-mkrescue -o bos.iso iso
