#!/bin/sh

set -e
. script/clean

make -C bos bos.kernel

mkdir -p iso
mkdir -p iso/boot
mkdir -p iso/boot/grub

cp bos/bos.kernel iso/boot/kernel
cat > iso/boot/grub/grub.cfg << EOF
menuentry "BOS" {
	echo "Loading ${kernel}..."
	multiboot /boot/kernel
	boot
}
EOF
grub-mkrescue -o bos.iso iso
